kind: configMap
apiversion: v1
metadata:
    name: backend
    namespace: expense
data: 
  DB_HOST: mysql  # mysql component service name

---
  
kind: Deployment
apiVersion: app/v1
metadata:
   name: backend
   namespace: expense
   # these labels are deployment related labels.
   labels: 
     component: nginx
     project: expense
     tier: app
   spec:
     replicas: 2
     selector:
        matchLabels:
          component: nginx
          project: expense
          tier: app
    # pod defination
template:
  metadata: 
    Labels:
      component: backend
      project: expense
      tier: app
  spec:
   containers:
   - name: backend
     image: joindevops/mysql:v1.0
     resources:
       requests:
         cpu: "100m"
         memory: "128Mi"
       limits:
        cpu: "150m"
        memory: "256Mi"

     envFrom:
      configMapKeyRef:
       name: backend
       

---

apiversion: v1
kind: service
metadata: 
 name: nginx
spec: 
 selector:
      name: front-end
      project: expense
      component: frontend
      environment: dev
ports:
    - protocol: TCP
      port: 8080  #service-port
      targetport: 8080 #target-port